### ISSUE TITLE
v3: Unaligned 64-bit atmoic operation panic during heartbeat

### ISSUE THREAD

**Issue by kingultron99** [diamondburned/arikawa#325]
Attempting to run my bot on my raspberry pi 1 model B, causes a panic from the ws heartbeat.
Note: this *is* a 32bit armv6 system.

I *would* run this on a different system or get a newer raspberry pi, but i dont have the money are another machine, even for cloud hosting, plus this is convenient and moves load away from my pc

here's the stack trace:
```
panic: unaligned 64-bit atomic operation

goroutine 27 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x18aa92c)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/diamondburned/arikawa/v3/internal/heart.(*AtomicDuration).Get(...)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.2/internal/heart/heart.go:40
github.com/diamondburned/arikawa/v3/internal/heart.(*Pacemaker).Pace(0x18aa92c)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.2/internal/heart/heart.go:117 +0x4c
github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).startLoop(0x18aa92c)
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.2/utils/wsutil/heart.go:111 +0x174
github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).StartBeating.func1()
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.2/utils/wsutil/heart.go:81 +0x24
created by github.com/diamondburned/arikawa/v3/utils/wsutil.(*PacemakerLoop).StartBeating
        /home/pi/go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.0.0-rc.2/utils/wsutil/heart.go:81 +0x214
exit status 2
```
system info:
```
go version go1.18.1 linux/arm
-------------------------------
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
``` 
This should be everything. if you need anything else, just let me know :)

**Comment by kingultron99** [comment]
Just found [this article](https://go101.org/article/memory-layout.html) while googling around. this might be helpfull for this issue. 
it explains golangs memory layout and ways to align 64bit words for 32 bit systems.

**Comment by diamondburned** [comment]
Can you try latest commit df0fa66c29b7d13d91b26389338635ae8a4f5f03?

**Comment by kingultron99** [comment]
as it turns out, my bot was rather out of date. currently rewriting some things that broke in the update. i'll post again here if the issue returns after im done.

**Comment by kingultron99** [comment]
looks like this issue is fixed on the latest commit 👍🏻
