### ISSUE TITLE
v3: Unlock of already unlocked mutex on nil body

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/arikawa#359]
```
2022/12/06 18:26:08 Discord API: GET /api/v9/channels/1048525374616768574/messages
2022/12/06 18:26:08 Discord API: GET /api/v9/channels/1048525374616768574/messages: 429 Too Many Requests
2022/12/06 18:26:08 Discord API: GET /api/v9/channels/1048525374616768574/messages
2022/12/06 18:26:08 Discord API: GET /api/v9/channels/1048525374616768574/messages nil response
panic: Unlock of already unlocked mutex.

goroutine 33729 [running]:
github.com/diamondburned/arikawa/v3/internal/moreatomic.(*CtxMutex).Unlock(...)
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/internal/moreatomic/mutex.go:41
github.com/diamondburned/arikawa/v3/api/rate.(*Limiter).Acquire(0xc00011fb00, {0x2067f80, 0xc00829c510}, {0xc00343a5d3, 0x2d})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/api/rate/rate.go:157 +0x3ab
github.com/diamondburned/arikawa/v3/api.(*Client).InjectRequest(0xc0002e3980, {0x20691e0, 0xc005a76700})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/api/api.go:86 +0x1d6
github.com/diamondburned/arikawa/v3/utils/httputil.(*Client).applyOptions(0xc0000b1b68?, {0x20691e0, 0xc005a76700}, {0xc0000b1dd8, 0x1, 0xc00343a5c0?})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/utils/httputil/client.go:80 +0x65
github.com/diamondburned/arikawa/v3/utils/httputil.(*Client).request(0xc008846310, {0x1d33b9c, 0x3}, {0xc00343a5c0, 0x40}, {0xc0000b1dd8, 0x1, 0x1})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/utils/httputil/client.go:209 +0x22f
github.com/diamondburned/arikawa/v3/utils/httputil.(*Client).Request(0x40?, {0x1d33b9c?, 0x9?}, {0xc00343a5c0?, 0xc00343a5c0?}, {0xc0000b1dd8?, 0xc0000b1d20?, 0xc00829c480?})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/utils/httputil/client.go:170 +0x45
github.com/diamondburned/arikawa/v3/utils/httputil.(*Client).RequestJSON(0xc009388858?, {0x19e9d40, 0xc0086cf230}, {0x1d33b9c?, 0x10000000000?}, {0xc00343a5c0?, 0x5720?}, {0xc0000b1dd8, 0x1, 0x1})
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/utils/httputil/client.go:143 +0x89
github.com/diamondburned/arikawa/v3/api.(*Client).messagesRange(0xc00510c480, 0x0?, 0x0, 0x0, 0x0, 0xe8d1c45dc04103e?)
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/api/message.go:182 +0x1aa
github.com/diamondburned/arikawa/v3/api.(*Client).MessagesBefore(0xc0007476c8?, 0xc000a01bf0?, 0x0, 0x2d)
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/api/message.go:79 +0x111
github.com/diamondburned/arikawa/v3/state.(*State).Messages(0xc0050c2240, 0x0?, 0x2d)
	/home/diamond/.go/pkg/mod/github.com/diamondburned/arikawa/v3@v3.1.1-0.20221205015406-73285954a1e9/state/state.go:652 +0x1fb
github.com/diamondburned/gtkcord4/internal/gtkcord/message.(*View).load.func1()
	/home/diamond/Scripts/gotk4/gtkcord4/internal/gtkcord/message/view.go:323 +0x45
github.com/diamondburned/gotkit/gtkutil.Async.func1()
	/home/diamond/.go/pkg/mod/github.com/diamondburned/gotkit@v0.0.0-20220927204852-c6db6b04288f/gtkutil/gtkutil.go:302 +0x33
created by github.com/diamondburned/gotkit/gtkutil.Async
	/home/diamond/.go/pkg/mod/github.com/diamondburned/gotkit@v0.0.0-20220927204852-c6db6b04288f/gtkutil/gtkutil.go:301 +0xaa
```

**Comment by diamondburned** [comment]
Closing stale bug.
